name: LivingGlass
options:
  bundleIdPrefix: com.taigrr
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  minimumXcodeGenVersion: "2.38"

targets:
  LivingGlass:
    type: application
    platform: macOS
    sources:
      - path: Sources
        type: group
    resources:
      - path: Resources
        type: group
      - path: icon.iconset
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taigrr.LivingGlass
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: "2"
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: LivingGlass.entitlements
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        METAL_COMPILER_FLAGS: ""
        MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      debug:
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      release:
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        MTL_ENABLE_DEBUG_INFO: "NO"
    entitlements:
      path: LivingGlass.entitlements
    info:
      path: Info.plist
    preBuildScripts:
      - name: "Compile Metal Shaders"
        script: |
          xcrun -sdk macosx metal -c "${SRCROOT}/Sources/Shaders.metal" -o "${DERIVED_FILE_DIR}/Shaders.air"
          xcrun -sdk macosx metallib "${DERIVED_FILE_DIR}/Shaders.air" -o "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/default.metallib"
        inputFiles:
          - $(SRCROOT)/Sources/Shaders.metal
        outputFiles:
          - $(BUILT_PRODUCTS_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/default.metallib

  LivingGlassScreenSaver:
    type: bundle
    platform: macOS
    sources:
      - path: Sources/GameEngine.swift
      - path: Sources/MetalRenderer.swift
      - path: Sources/GameOfLifeView.swift
      - path: Sources/Preferences.swift
      - path: ScreenSaver/LivingGlassView.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taigrr.LivingGlass.saver
        WRAPPER_EXTENSION: saver
        INFOPLIST_FILE: ScreenSaver/Info.plist
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        LD_RUNPATH_SEARCH_PATHS: "@loader_path/../Frameworks"
        PRODUCT_NAME: LivingGlass
        MODULE_NAME: LivingGlass

schemes:
  LivingGlass:
    build:
      targets:
        LivingGlass: all
    run:
      config: Debug
    archive:
      config: Release
